### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cliffordx** [hkgnp/logseq-powerblocks-plugin#1]
I'm reading "Four Thousand Weeks" by Oliver Burkeman. I wanted to embed the week since my birth date in the format 1,234.0 1,234 is the number of weeks then 0 is tuesday, 1 is wednesday so on and so forth. I think this is doable given you are expert on this. Thank you in advance.

**Comment by benjypng** [comment]
This is now available in the latest version using the syntax `<%WEEKSSINCEDATE:28 Feb 1990%>`. For the day, you can use the syntax `<%DAY%>`.

Side note: It is odd that `0` is Tuesday though.
