### ISSUE TITLE
[Feature Request]: Add syntax to query properties 

### ISSUE THREAD

**Issue by kings2u** [hkgnp/logseq-powerblocks-plugin#2]
### Plugin Version

0.0.32

### Logseq Version

current as of today 

### Request 

Thank you for this genius plugin, it’s just what I’ve been looking for. 

I would love a syntax that allows us to query the values of a page's properties. The default could be the properties of the current page, but could be expanded to allow a user to also specify another page's properties to query. 

Make my dreams come true?

**Comment by benjypng** [comment]
I roughly understand the feature request but could you provide a specific example to be sure?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: kings2u ***@***.***>
Sent: Wednesday, April 5, 2023 9:55:16 AM
To: hkgnp/logseq-powerblocks-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hkgnp/logseq-powerblocks-plugin] [Feature Request]: Add syntax to query properties (Issue #2)


Plugin Version

0.0.32

Logseq Version

current as of today

What browsers are you seeing the problem on?

Windows

What happened?

Thank you for this genius plugin, it’s just what I’ve been looking for.

I would love a syntax that allows us to query the values of a page's properties. The default could be the properties of the current page, but could be expanded to allow a user to also specify another page's properties to query.

Make my dreams come true?

**Comment by kings2u** [comment]
Sure! So let's say we have a [[page 1]] with a page property of `DOB:: 1/1/2000`. I’d love for a template to insert the DOB as needed. 

So, for example, the syntax could look like: `I was born on <%PROPERTY: [[page 1]] DOB%>.` And it would resolve to `I was born on 1/1/2000.` So the reference would require the page name and a specific property of the page.

I think you already have the start of this functionality with the syntax `<$CURRENTPAGENAME%>`, but being able to reference a page's properties would allow the creation of very sophisticated templates for things like emails, letters, and other repetitive information. 

Thanks again for considering this feature!

**Comment by benjypng** [comment]
This is available in the latest update. For your example, separate your page with a comma, e.g.
`I was born on <%GETPROPERTY:[[page 1]],DOB%>.`
