### ISSUE TITLE
Feature Request: Re-arrange popup

### ISSUE THREAD

**Issue by cliffordx** [hkgnp/logseq-powerblocks-plugin#3]
### Plugin Version

0.0.34-alpha

### Logseq Version

v.0.9.14

### What browsers are you seeing the problem on?

MacOS

### What happened?

After invoking `/,` the list shows up but sometimes I wanted it arranged according to what I used first. Can it be possible?

Thank you.

 
<img width="301" alt="Screenshot 2023-08-21 at 9 37 24 AM" src="https://github.com/hkgnp/logseq-powerblocks-plugin/assets/7141739/828c36ef-90dc-4593-b9f8-ee1e76fafe48">

**Comment by benjypng** [comment]
The new menu allows you to dynamically search based on what you type. Should be able to offer a better experience.
