### ISSUE TITLE
[feature request]: sticky buttons

### ISSUE THREAD

**Issue by poelzi** [hkgnp/logseq-powerblocks-plugin#4]
### Plugin Version

0.1

### Logseq Version

0.9.2

### What browsers are you seeing the problem on?

Linux

### What happened?

It would be nice if there would be a property on the powerblock block  that will make the button sticky.
Pressing the button will create a new node with the template but the button will stay.
Also an option for indent level would be nice where the new node will be placed

**Comment by benjypng** [comment]
Thanks for the suggestion. I may not completely understand what you mean. Is there an example you can use to explain?

**Comment by benjypng** [comment]
Available in latest version.
