### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by jaker-dotcom** [hkgnp/logseq-powerblocks-plugin#5]
### Plugin Version

egal

### Logseq Version

egal

### What browsers are you seeing the problem on?

Linux

### What happened?

in the readme two macros are made with dollar signs instead of percentage. 
Specifically  
<$CURRENTPAGENAME%> 
<$CURRENTPAGEURL%> 
don't work but should be

<%CURRENTPAGENAME%> 
<%CURRENTPAGEURL%>

**Comment by benjypng** [comment]
Fixed. Thanks!
